/**
 * بيانات الأقسام (الاسم والوصف والأيقونة) — بدون صور.
 * الصور تُقرأ تلقائياً من مجلد public/images حسب اسم الملف. انظر lib/categories.ts
 */
export type CategoryMeta = {
  slug: string
  name: string
  nameEn: string
  description: string
  descriptionEn: string
  icon: string
}

export const categoryMeta: CategoryMeta[] = [
  {
    slug: 'executive-desks',
    name: 'مكاتب رئاسية',
    nameEn: 'Executive Desks',
    description: 'مكاتب فاخرة بتصميمات تليق بمكتب المدير العام، بخامات ولمسات نهائية راقية.',
    descriptionEn: 'Luxury desks with premium materials and finishes, worthy of a CEO office.',
    icon: 'Crown',
  },
  {
    slug: 'executive-lounge',
    name: 'جلوس رئاسي',
    nameEn: 'Executive Lounge Seating',
    description: 'أطقم جلوس فاخرة تكمل المكتب الرئاسي وتليق باستقبال كبار الزوار.',
    descriptionEn: 'Premium sofa sets that complete the executive office and host VIP guests.',
    icon: 'Sofa',
  },
  {
    slug: 'manager-desks',
    name: 'مكاتب مدراء إدارات',
    nameEn: 'Department Manager Desks',
    description: 'مكاتب عملية بمساحة عمل مريحة ووحدات تخزين جانبية.',
    descriptionEn: 'Practical desks with comfortable work space and side storage units.',
    icon: 'Briefcase',
  },
  {
    slug: 'manager-lounge',
    name: 'جلوس مكاتب مدراء إدارات',
    nameEn: 'Manager Office Seating',
    description: 'أطقم جلوس وكراسي زوار تكمل مكتب مدير الإدارة بتنسيق متناسق.',
    descriptionEn: 'Sofa sets and visitor chairs that complete a manager office.',
    icon: 'Armchair',
  },
  {
    slug: 'staff-desks',
    name: 'مكاتب موظفين',
    nameEn: 'Staff Desks',
    description: 'مكاتب وكراسي للموظفين بتصميم عملي ومتين يناسب الاستخدام اليومي.',
    descriptionEn: 'Practical, durable desks and chairs for everyday office use.',
    icon: 'Users',
  },
  {
    slug: 'secretary-desks',
    name: 'مكاتب سكرتارية',
    nameEn: 'Secretary Desks',
    description: 'مكاتب سكرتارية بوحدات تخزين ومساحة عمل منظمة تناسب مكتب المدير.',
    descriptionEn: 'Secretary desks with storage units and an organised work surface.',
    icon: 'Laptop',
  },
  {
    slug: 'workstations',
    name: 'ويرك ستيشن',
    nameEn: 'Workstations',
    description: 'وحدات عمل جماعية بفواصل ووحدات تخزين لاستغلال المساحة بكفاءة.',
    descriptionEn: 'Shared work units with partitions and storage to use space efficiently.',
    icon: 'LayoutGrid',
  },
  {
    slug: 'reception-counters',
    name: 'كاونترات إستقبال',
    nameEn: 'Reception Counters',
    description: 'كاونترات ومكاتب استقبال بمقاسات وتصميمات مختلفة تناسب المداخل والصالات.',
    descriptionEn: 'Reception counters and desks in various sizes and designs for lobbies and halls.',
    icon: 'Store',
  },
  {
    slug: 'meeting-tables',
    name: 'ترابيزات اجتماعات',
    nameEn: 'Meeting Tables',
    description: 'ترابيزات اجتماعات بمقاسات مختلفة تتسع من 6 إلى 20 شخصاً.',
    descriptionEn: 'Meeting tables in different sizes, seating from 6 to 20 people.',
    icon: 'Presentation',
  },
  {
    slug: 'safes',
    name: 'خزنات مصفحة ضد الحريق والرصاص',
    nameEn: 'Fire & Bullet Resistant Safes',
    description: 'خزنات آمنة بأقفال رقمية ومفتاحية لحماية المستندات والنقود.',
    descriptionEn: 'Secure safes with digital and key locks to protect documents and cash.',
    icon: 'ShieldCheck',
  },
  {
    slug: 'armored-filing',
    name: 'فايل كابين مصفح ضد الحريق والرصاص',
    nameEn: 'Fire & Bullet Resistant Filing Cabinets',
    description: 'دواليب ملفات مصفحة بأدراج مقاومة للحريق لحفظ الأوراق المهمة.',
    descriptionEn: 'Armoured filing cabinets with fire-resistant drawers for important papers.',
    icon: 'FileLock2',
  },
  {
    slug: 'steel-filing',
    name: 'فايل كابين حديد',
    nameEn: 'Steel Filing Cabinets',
    description: 'دواليب ملفات حديد بأدراج انزلاقية وأقفال أمان.',
    descriptionEn: 'Steel filing cabinets with sliding drawers and safety locks.',
    icon: 'Files',
  },
  {
    slug: 'steel-cabinets',
    name: 'دولاب حديد',
    nameEn: 'Steel Cabinets',
    description: 'دواليب حديد بأبواب زجاجية أو معدنية لتخزين الملفات والأدوات.',
    descriptionEn: 'Steel cabinets with glass or metal doors for files and tools.',
    icon: 'Archive',
  },
  {
    slug: 'steel-lockers',
    name: 'لوكرات حديد',
    nameEn: 'Steel Lockers',
    description: 'لوكرات بعيون متعددة للمصانع والمدارس والنوادي وأماكن العمل.',
    descriptionEn: 'Multi-door lockers for factories, schools, clubs and workplaces.',
    icon: 'LockKeyhole',
  },
  {
    slug: 'steel-sofas',
    name: 'كنب حديد',
    nameEn: 'Steel Benches',
    description: 'كنب وبنوك انتظار حديد للاستقبال والعيادات وصالات الانتظار.',
    descriptionEn: 'Steel waiting benches for reception areas, clinics and waiting halls.',
    icon: 'Armchair',
  },
  {
    slug: 'padded-sofas',
    name: 'كنب حديد مبطن',
    nameEn: 'Upholstered Sofas',
    description: 'أطقم كنب مبطنة بخامات فاخرة للمكاتب والاستقبال والمنزل.',
    descriptionEn: 'Sofa sets upholstered in premium materials for offices, reception areas and homes.',
    icon: 'Sofa',
  },
  {
    slug: 'leather-chairs',
    name: 'كراسي جلد فاخرة',
    nameEn: 'Premium Leather Chairs',
    description: 'كراسي مكتب بجلد طبيعي وصناعي فاخر بمساند مريحة وقواعد متينة.',
    descriptionEn: 'Office chairs in genuine and synthetic leather with comfortable support and sturdy bases.',
    icon: 'RockingChair',
  },
  {
    slug: 'medical-chairs',
    name: 'كراسي طبية دوار وثابت',
    nameEn: 'Medical Chairs — Swivel & Fixed',
    description: 'كراسي طبية دوارة وثابتة للعيادات والمستشفيات بارتفاع قابل للضبط.',
    descriptionEn: 'Swivel and fixed medical chairs for clinics and hospitals with adjustable height.',
    icon: 'Stethoscope',
  },
  {
    slug: 'lab-chairs',
    name: 'كراسي معامل دوار وثابت',
    nameEn: 'Laboratory Chairs — Swivel & Fixed',
    description: 'كراسي معامل دوارة وثابتة بخامات مقاومة للمواد الكيميائية.',
    descriptionEn: 'Swivel and fixed laboratory chairs in chemical-resistant materials.',
    icon: 'FlaskConical',
  },
  {
    slug: 'hall-chairs',
    name: 'كراسي قاعات ومسارح',
    nameEn: 'Auditorium & Theatre Seating',
    description: 'كراسي مسرح بمساند طي وأرجل ثابتة للقاعات والمدرجات.',
    descriptionEn: 'Theatre seats with folding arms and fixed legs for halls and lecture rooms.',
    icon: 'Theater',
  },
  {
    slug: 'vip-hall-chairs',
    name: 'كرسي مسرح وقاعات VIP',
    nameEn: 'VIP Theatre & Hall Seats',
    description: 'كراسي VIP بمساند قابلة للاستلقاء وخامات جلد فاخرة.',
    descriptionEn: 'VIP recliner seats with premium leather upholstery.',
    icon: 'Star',
  },
  {
    slug: 'podiums',
    name: 'منصات ندوات',
    nameEn: 'Seminar Podiums',
    description: 'منصات خطابة ومنابر للندوات والمؤتمرات بتصميمات خشبية وعصرية.',
    descriptionEn: 'Lecterns and podiums for seminars and conferences in wooden and modern designs.',
    icon: 'Megaphone',
  },
  {
    slug: 'bank-equipment',
    name: 'مستلزمات البنوك والصرافات',
    nameEn: 'Bank & Exchange Equipment',
    description: 'تجهيزات ومستلزمات فروع البنوك ومكاتب الصرافة.',
    descriptionEn: 'Equipment and fittings for bank branches and exchange offices.',
    icon: 'Banknote',
  },
  {
    slug: 'sound-systems',
    name: 'أنظمة الصوتيات للقاعات',
    nameEn: 'Hall Sound Systems',
    description: 'ميكروفونات مؤتمرات وأنظمة صوت متكاملة للقاعات وغرف الاجتماعات.',
    descriptionEn: 'Conference microphones and complete sound systems for halls and meeting rooms.',
    icon: 'Mic',
  },
]
